apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: creaplanesopo-outputs
  namespace: creaplanesopo
  labels:
    app.kubernetes.io/name: creaplanesopo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: lvms-vg1
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: creaplanesopo-backups
  namespace: creaplanesopo
  labels:
    app.kubernetes.io/name: creaplanesopo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: lvms-vg1
  resources:
    requests:
      storage: 5Gi
